<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <title>{{ $meta['title'] ?? 'Report' }}</title>
    <style>
        @page { size: A4; margin: 14mm 12mm; }
        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            color: #1f2937;
            font-size: 10pt;
            line-height: 1.45;
        }
        header {
            border-bottom: 2px solid #0f766e;
            padding-bottom: 10px;
            margin-bottom: 18px;
            display: flex;
            justify-content: space-between;
            align-items: flex-end;
        }
        header .brand { font-size: 14pt; font-weight: 700; color: #0f766e; }
        header .meta { text-align: right; font-size: 9pt; color: #4b5563; }
        h1 {
            font-size: 16pt;
            margin: 0 0 4px;
            color: #111827;
            font-weight: 700;
        }
        h1.sub {
            font-size: 10pt;
            color: #6b7280;
            font-weight: 400;
            margin: 0 0 16px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 18px;
        }
        thead {
            background: #0f766e;
            color: #ffffff;
        }
        thead th {
            text-align: left;
            padding: 7px 8px;
            font-size: 9.5pt;
            font-weight: 600;
        }
        thead th.right { text-align: right; }
        tbody td {
            padding: 6px 8px;
            border-bottom: 1px solid #e5e7eb;
            font-size: 9.5pt;
        }
        tbody td.right { text-align: right; }
        tbody tr:nth-child(even) { background: #f9fafb; }
        .empty {
            text-align: center;
            padding: 30px;
            color: #9ca3af;
            font-style: italic;
        }
        .summary {
            margin-top: 4px;
            margin-left: auto;
            width: 45%;
            border-collapse: collapse;
        }
        .summary td {
            padding: 6px 8px;
            font-size: 10pt;
        }
        .summary td.label { color: #4b5563; }
        .summary td.value { text-align: right; font-weight: 600; }
        .summary tr.grand td {
            border-top: 2px solid #0f766e;
            font-size: 11pt;
        }
        footer {
            position: fixed;
            bottom: 6mm;
            left: 12mm;
            right: 12mm;
            font-size: 8.5pt;
            color: #9ca3af;
            text-align: center;
            border-top: 1px solid #e5e7eb;
            padding-top: 4px;
        }
    </style>
</head>
<body>
    <header>
        <div>
            <div class="brand">{{ $meta['client'] ?? 'PMS' }}</div>
        </div>
        <div class="meta">
            {{ __('Generated') }}: {{ $meta['generated_at'] ?? now()->format('d/m/Y H:i') }}
        </div>
    </header>

    <h1>{{ $meta['title'] ?? 'Report' }}</h1>
    @if (! empty($meta['subtitle']))
        <h1 class="sub">{{ $meta['subtitle'] }}</h1>
    @endif
    @if (! empty($meta['period']))
        <h1 class="sub">{{ __('Period') }}: {{ $meta['period'] }}</h1>
    @endif

    <table>
        <thead>
            <tr>
                @foreach ($columns as $col)
                    <th class="{{ ($col['align'] ?? 'left') === 'right' ? 'right' : '' }}">{{ $col['label'] }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
        @forelse ($rows as $row)
            <tr>
                @foreach ($columns as $col)
                    <td class="{{ ($col['align'] ?? 'left') === 'right' ? 'right' : '' }}">{{ $row[$col['key']] ?? '' }}</td>
                @endforeach
            </tr>
        @empty
            <tr>
                <td class="empty" colspan="{{ count($columns) }}">{{ __('No data for this period.') }}</td>
            </tr>
        @endforelse
        </tbody>
    </table>

    @if (! empty($summary))
        <table class="summary">
            @foreach ($summary as $label => $value)
                @php $isGrand = $loop->last; @endphp
                <tr class="{{ $isGrand ? 'grand' : '' }}">
                    <td class="label">{{ $label }}</td>
                    <td class="value">{{ $value }}</td>
                </tr>
            @endforeach
        </table>
    @endif

    <footer>
        {{ __('Generated by PMS') }} &middot; {{ now()->format('d/m/Y H:i') }}
    </footer>
</body>
</html>
