<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Receipt = the official proof of payment given to the renter. One per
 * completed payment, auto-generated by an observer on Payment save.
 *
 * receipt_number format: `RCP-{tenant_slug}-{year}-{padded_number}`
 * — same sequence machinery as invoice_number, just a different prefix.
 *
 * pdf_path is the B2 (or local in dev) path written by ReceiptPdfGenerator.
 * Per-channel "sent_at" timestamps allow idempotent retries — if a job sends
 * the same receipt twice, we update the timestamp without writing a duplicate
 * row.
 *
 * No soft deletes — receipts are issued or never issued. If you need to void
 * one, cancel the underlying payment (which cascades).
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('receipts', function (Blueprint $table) {
            $table->id();

            $table->string('tenant_id');
            $table->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete();

            $table->uuid('payment_id');
            $table->foreign('payment_id')->references('id')->on('payments')->cascadeOnDelete();

            $table->string('receipt_number');

            $table->string('pdf_path')->nullable();
            // Filled lazily by ReceiptPdfGenerator on first download/send.

            $table->timestamp('issued_at');

            $table->timestamp('sent_via_email_at')->nullable();
            $table->timestamp('sent_via_whatsapp_at')->nullable();

            $table->timestamps();

            $table->index('tenant_id');
            $table->index(['tenant_id', 'payment_id']);
            $table->unique(['tenant_id', 'receipt_number']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('receipts');
    }
};
